name: my 1st workflow 

on: [push]

jobs:
  job-linux:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "hey Harindra"
      - name: multiple script
        run: |
          node -v
          npm -v
      - name: python command
        run: |
          import platform
          print(platform.processor())
        shell: python 
  job-windows:
    runs-on: windows-latest
    needs: ["job-linux"]  
    steps:
      - name: Get work DIR
        run: pwd
        shell: bash  
