name: my 1st workflow 

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "hey Harindra"
      - name: multiple script
        run: |
          node -v
          npm -v
      - name: python command
        run: |
          import platform
          print(platform.processor())
        shell: python 
  run-windows-cmd:
    runs-on: windows-latest
    steps:
      - name: Get work DIR
      PowerShell
        run: Get-Location
        run: pwd
        shell: bash  
